// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/print.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrintRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	MachineCode          string   `protobuf:"bytes,3,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	OriginId             string   `protobuf:"bytes,5,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Sign                 string   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintRequest) Reset()         { *m = PrintRequest{} }
func (m *PrintRequest) String() string { return proto.CompactTextString(m) }
func (*PrintRequest) ProtoMessage()    {}
func (*PrintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{0}
}

func (m *PrintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintRequest.Unmarshal(m, b)
}
func (m *PrintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintRequest.Marshal(b, m, deterministic)
}
func (m *PrintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintRequest.Merge(m, src)
}
func (m *PrintRequest) XXX_Size() int {
	return xxx_messageInfo_PrintRequest.Size(m)
}
func (m *PrintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrintRequest proto.InternalMessageInfo

func (m *PrintRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *PrintRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *PrintRequest) GetMachineCode() string {
	if m != nil {
		return m.MachineCode
	}
	return ""
}

func (m *PrintRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PrintRequest) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *PrintRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PrintRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PrintRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PrintReply struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription     string   `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	Body                 *Body    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintReply) Reset()         { *m = PrintReply{} }
func (m *PrintReply) String() string { return proto.CompactTextString(m) }
func (*PrintReply) ProtoMessage()    {}
func (*PrintReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{1}
}

func (m *PrintReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintReply.Unmarshal(m, b)
}
func (m *PrintReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintReply.Marshal(b, m, deterministic)
}
func (m *PrintReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintReply.Merge(m, src)
}
func (m *PrintReply) XXX_Size() int {
	return xxx_messageInfo_PrintReply.Size(m)
}
func (m *PrintReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrintReply proto.InternalMessageInfo

func (m *PrintReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *PrintReply) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

func (m *PrintReply) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type OauthRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GrantType            string   `protobuf:"bytes,2,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OauthRequest) Reset()         { *m = OauthRequest{} }
func (m *OauthRequest) String() string { return proto.CompactTextString(m) }
func (*OauthRequest) ProtoMessage()    {}
func (*OauthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{2}
}

func (m *OauthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OauthRequest.Unmarshal(m, b)
}
func (m *OauthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OauthRequest.Marshal(b, m, deterministic)
}
func (m *OauthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OauthRequest.Merge(m, src)
}
func (m *OauthRequest) XXX_Size() int {
	return xxx_messageInfo_OauthRequest.Size(m)
}
func (m *OauthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OauthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OauthRequest proto.InternalMessageInfo

func (m *OauthRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *OauthRequest) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *OauthRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *OauthRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *OauthRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OauthRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ForeignOauthRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MachineCode          string   `protobuf:"bytes,2,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	Msign                string   `protobuf:"bytes,3,opt,name=msign,proto3" json:"msign,omitempty"`
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Sign                 string   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForeignOauthRequest) Reset()         { *m = ForeignOauthRequest{} }
func (m *ForeignOauthRequest) String() string { return proto.CompactTextString(m) }
func (*ForeignOauthRequest) ProtoMessage()    {}
func (*ForeignOauthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{3}
}

func (m *ForeignOauthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForeignOauthRequest.Unmarshal(m, b)
}
func (m *ForeignOauthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForeignOauthRequest.Marshal(b, m, deterministic)
}
func (m *ForeignOauthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForeignOauthRequest.Merge(m, src)
}
func (m *ForeignOauthRequest) XXX_Size() int {
	return xxx_messageInfo_ForeignOauthRequest.Size(m)
}
func (m *ForeignOauthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForeignOauthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForeignOauthRequest proto.InternalMessageInfo

func (m *ForeignOauthRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ForeignOauthRequest) GetMachineCode() string {
	if m != nil {
		return m.MachineCode
	}
	return ""
}

func (m *ForeignOauthRequest) GetMsign() string {
	if m != nil {
		return m.Msign
	}
	return ""
}

func (m *ForeignOauthRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *ForeignOauthRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ForeignOauthRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForeignOauthRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PicturePrintRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	MachineCode          string   `protobuf:"bytes,3,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	PictureUrl           string   `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	OriginId             string   `protobuf:"bytes,5,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Sign                 string   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PicturePrintRequest) Reset()         { *m = PicturePrintRequest{} }
func (m *PicturePrintRequest) String() string { return proto.CompactTextString(m) }
func (*PicturePrintRequest) ProtoMessage()    {}
func (*PicturePrintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{4}
}

func (m *PicturePrintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicturePrintRequest.Unmarshal(m, b)
}
func (m *PicturePrintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicturePrintRequest.Marshal(b, m, deterministic)
}
func (m *PicturePrintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicturePrintRequest.Merge(m, src)
}
func (m *PicturePrintRequest) XXX_Size() int {
	return xxx_messageInfo_PicturePrintRequest.Size(m)
}
func (m *PicturePrintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PicturePrintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PicturePrintRequest proto.InternalMessageInfo

func (m *PicturePrintRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *PicturePrintRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *PicturePrintRequest) GetMachineCode() string {
	if m != nil {
		return m.MachineCode
	}
	return ""
}

func (m *PicturePrintRequest) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *PicturePrintRequest) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *PicturePrintRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PicturePrintRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PicturePrintRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ExpressPrintRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	MachineCode          string   `protobuf:"bytes,3,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	OriginId             string   `protobuf:"bytes,4,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Sign                 string   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	Timestamp            string   `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content              string   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpressPrintRequest) Reset()         { *m = ExpressPrintRequest{} }
func (m *ExpressPrintRequest) String() string { return proto.CompactTextString(m) }
func (*ExpressPrintRequest) ProtoMessage()    {}
func (*ExpressPrintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{5}
}

func (m *ExpressPrintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressPrintRequest.Unmarshal(m, b)
}
func (m *ExpressPrintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressPrintRequest.Marshal(b, m, deterministic)
}
func (m *ExpressPrintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressPrintRequest.Merge(m, src)
}
func (m *ExpressPrintRequest) XXX_Size() int {
	return xxx_messageInfo_ExpressPrintRequest.Size(m)
}
func (m *ExpressPrintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressPrintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressPrintRequest proto.InternalMessageInfo

func (m *ExpressPrintRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ExpressPrintRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ExpressPrintRequest) GetMachineCode() string {
	if m != nil {
		return m.MachineCode
	}
	return ""
}

func (m *ExpressPrintRequest) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *ExpressPrintRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExpressPrintRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ExpressPrintRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ExpressPrintRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PrintSetVoiceRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	MachineCode          string   `protobuf:"bytes,3,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsFile               string   `protobuf:"bytes,5,opt,name=is_file,json=isFile,proto3" json:"is_file,omitempty"`
	Aid                  string   `protobuf:"bytes,6,opt,name=aid,proto3" json:"aid,omitempty"`
	Sign                 string   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	Id                   string   `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintSetVoiceRequest) Reset()         { *m = PrintSetVoiceRequest{} }
func (m *PrintSetVoiceRequest) String() string { return proto.CompactTextString(m) }
func (*PrintSetVoiceRequest) ProtoMessage()    {}
func (*PrintSetVoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e13c50d52a05c362, []int{6}
}

func (m *PrintSetVoiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintSetVoiceRequest.Unmarshal(m, b)
}
func (m *PrintSetVoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintSetVoiceRequest.Marshal(b, m, deterministic)
}
func (m *PrintSetVoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintSetVoiceRequest.Merge(m, src)
}
func (m *PrintSetVoiceRequest) XXX_Size() int {
	return xxx_messageInfo_PrintSetVoiceRequest.Size(m)
}
func (m *PrintSetVoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintSetVoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrintSetVoiceRequest proto.InternalMessageInfo

func (m *PrintSetVoiceRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetMachineCode() string {
	if m != nil {
		return m.MachineCode
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetIsFile() string {
	if m != nil {
		return m.IsFile
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetAid() string {
	if m != nil {
		return m.Aid
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PrintSetVoiceRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*PrintRequest)(nil), "proto.PrintRequest")
	proto.RegisterType((*PrintReply)(nil), "proto.PrintReply")
	proto.RegisterType((*OauthRequest)(nil), "proto.OauthRequest")
	proto.RegisterType((*ForeignOauthRequest)(nil), "proto.ForeignOauthRequest")
	proto.RegisterType((*PicturePrintRequest)(nil), "proto.PicturePrintRequest")
	proto.RegisterType((*ExpressPrintRequest)(nil), "proto.ExpressPrintRequest")
	proto.RegisterType((*PrintSetVoiceRequest)(nil), "proto.PrintSetVoiceRequest")
}

func init() { proto.RegisterFile("proto/print.proto", fileDescriptor_e13c50d52a05c362) }

var fileDescriptor_e13c50d52a05c362 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0x9d, 0x38, 0x89, 0x27, 0xf9, 0xfd, 0x68, 0x36, 0x91, 0xb0, 0x52, 0x50, 0x4b, 0x4e,
	0x95, 0x90, 0x5a, 0x29, 0x9c, 0x11, 0x88, 0x3f, 0xad, 0x7a, 0xa2, 0x4a, 0x0b, 0x57, 0xcb, 0x5d,
	0x0f, 0xe9, 0x0a, 0xdb, 0x6b, 0x76, 0x37, 0x88, 0xdc, 0x78, 0x16, 0x5e, 0x85, 0xb7, 0xe1, 0x86,
	0xc4, 0x81, 0x23, 0xf2, 0xee, 0xc6, 0x75, 0x1c, 0x57, 0xf4, 0x42, 0xc5, 0xc9, 0x3b, 0xdf, 0xcc,
	0x78, 0xf6, 0xfb, 0x66, 0x76, 0x60, 0x98, 0x0b, 0xae, 0xf8, 0x51, 0x2e, 0x58, 0xa6, 0x0e, 0xf5,
	0x99, 0x78, 0xfa, 0x33, 0x21, 0xc6, 0x43, 0x79, 0x9a, 0xf2, 0xcc, 0xb8, 0xa6, 0xdf, 0x1d, 0x18,
	0x9c, 0x15, 0xa1, 0x73, 0xfc, 0xb8, 0x44, 0xa9, 0xc8, 0x2e, 0xf8, 0x34, 0x61, 0x98, 0xa9, 0x90,
	0xc5, 0x81, 0xb3, 0xef, 0x1c, 0xf8, 0xf3, 0x9e, 0x01, 0x4e, 0x63, 0xf2, 0x08, 0x06, 0x11, 0xa5,
	0x28, 0x65, 0xa8, 0xf8, 0x07, 0xcc, 0x02, 0x57, 0xfb, 0xfb, 0x06, 0xbb, 0x28, 0xa0, 0x22, 0x24,
	0x8d, 0xe8, 0x15, 0xcb, 0x30, 0xa4, 0x3c, 0xc6, 0xa0, 0x65, 0x42, 0x2c, 0xf6, 0x92, 0xc7, 0x48,
	0x02, 0xe8, 0x52, 0x9e, 0x29, 0xcc, 0x54, 0xd0, 0xd6, 0xde, 0xb5, 0x59, 0x14, 0xe7, 0x82, 0x2d,
	0x58, 0x56, 0x14, 0xf7, 0x4c, 0x71, 0x03, 0x9c, 0xc6, 0x84, 0x40, 0x5b, 0xb2, 0x45, 0x16, 0x74,
	0x34, 0xae, 0xcf, 0xe4, 0x7f, 0x70, 0x59, 0x1c, 0x74, 0x35, 0xe2, 0xb2, 0x98, 0x3c, 0x00, 0x5f,
	0xb1, 0x14, 0xa5, 0x8a, 0xd2, 0x3c, 0xe8, 0xed, 0x3b, 0x07, 0xad, 0xf9, 0x35, 0x30, 0xcd, 0x01,
	0x2c, 0xd7, 0x3c, 0x59, 0x91, 0x31, 0x78, 0x28, 0x04, 0x17, 0x96, 0xa5, 0x31, 0xc8, 0x63, 0x18,
	0xea, 0x43, 0x18, 0xa3, 0xa4, 0x82, 0xe5, 0x8a, 0xf1, 0x35, 0xcf, 0x1d, 0xed, 0x78, 0x75, 0x8d,
	0x93, 0x3d, 0x68, 0x5f, 0xf2, 0x78, 0xa5, 0x49, 0xf6, 0x67, 0x7d, 0xa3, 0xe9, 0xe1, 0x0b, 0x1e,
	0xaf, 0xe6, 0xda, 0x31, 0xfd, 0xea, 0xc0, 0xe0, 0x4d, 0xb4, 0x54, 0x57, 0xb7, 0x92, 0xf7, 0x21,
	0xc0, 0x42, 0x44, 0x99, 0x0a, 0xd5, 0x2a, 0x47, 0x5b, 0xd4, 0xd7, 0xc8, 0xc5, 0x2a, 0xc7, 0x52,
	0x80, 0x56, 0x45, 0x80, 0x31, 0x78, 0x92, 0xf2, 0x1c, 0xad, 0x92, 0xc6, 0xd8, 0x94, 0xc1, 0xab,
	0xc9, 0x60, 0x45, 0xeb, 0xac, 0x45, 0x9b, 0x7e, 0x73, 0x60, 0x74, 0xcc, 0x05, 0xb2, 0x45, 0x76,
	0xfb, 0xbb, 0xd6, 0xfb, 0xec, 0x6e, 0xf7, 0x79, 0x0c, 0x5e, 0x5a, 0xb9, 0xb0, 0x31, 0x6e, 0xb8,
	0xf1, 0x9a, 0x9b, 0xb7, 0xd5, 0xdc, 0x4e, 0x73, 0x73, 0xbb, 0xf5, 0xe6, 0xfe, 0x72, 0x60, 0x74,
	0xc6, 0xa8, 0x5a, 0x0a, 0xbc, 0xeb, 0x81, 0xde, 0x83, 0x7e, 0x6e, 0x2a, 0x87, 0x4b, 0x91, 0x58,
	0x62, 0x60, 0xa1, 0xb7, 0x22, 0xf9, 0xdb, 0x73, 0xfd, 0xc3, 0x81, 0xd1, 0xeb, 0xcf, 0xb9, 0x40,
	0x29, 0xef, 0x9a, 0xfa, 0x06, 0xb3, 0x76, 0x8d, 0x99, 0x61, 0xe1, 0x95, 0x2c, 0x9a, 0x98, 0x6e,
	0x35, 0xd5, 0xaf, 0x8e, 0x6a, 0x65, 0x55, 0xf4, 0x36, 0x56, 0xc5, 0xf4, 0x8b, 0x0b, 0x63, 0x4d,
	0xf6, 0x1c, 0xd5, 0x3b, 0xce, 0x28, 0xfe, 0x13, 0x0b, 0xec, 0x3e, 0x74, 0x99, 0x0c, 0xdf, 0xb3,
	0x04, 0x2d, 0xed, 0x0e, 0x93, 0xc7, 0x2c, 0x41, 0xb2, 0x03, 0xad, 0xa8, 0x1c, 0xe6, 0xe2, 0x58,
	0x8a, 0xd1, 0xdd, 0x6a, 0x7b, 0xaf, 0xb9, 0xed, 0x7e, 0xad, 0xed, 0xb3, 0x9f, 0xae, 0xdd, 0xdd,
	0xe7, 0x28, 0x3e, 0x31, 0x8a, 0xe4, 0x08, 0x3c, 0x6d, 0x93, 0x91, 0xdd, 0x44, 0xd5, 0x69, 0x98,
	0x0c, 0x37, 0xc1, 0x62, 0x05, 0x3e, 0x87, 0x7b, 0x27, 0xa8, 0xec, 0xdb, 0x37, 0xf4, 0x27, 0x36,
	0xaa, 0x61, 0x21, 0x34, 0xfd, 0x61, 0x06, 0xbd, 0x13, 0x54, 0x26, 0x75, 0x5d, 0xf5, 0x4f, 0x39,
	0x4f, 0x61, 0x50, 0x7d, 0xa8, 0x65, 0xc9, 0x86, 0xd7, 0x7b, 0x43, 0x7a, 0x75, 0xd8, 0xcb, 0xf4,
	0x86, 0x17, 0xd0, 0x94, 0xfe, 0x0c, 0xfe, 0xdb, 0x98, 0x1b, 0xb2, 0x5b, 0x8d, 0xa9, 0x4d, 0x53,
	0xc3, 0x0f, 0x2e, 0x3b, 0x1a, 0x79, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x54, 0x12, 0x4e,
	0x69, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrintServiceClient is the client API for PrintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrintServiceClient interface {
	Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintReply, error)
	GetForeignToken(ctx context.Context, in *ForeignOauthRequest, opts ...grpc.CallOption) (*PrintReply, error)
	GetToken(ctx context.Context, in *OauthRequest, opts ...grpc.CallOption) (*PrintReply, error)
	PicturePrint(ctx context.Context, in *PicturePrintRequest, opts ...grpc.CallOption) (*PrintReply, error)
	ExpressPrint(ctx context.Context, in *ExpressPrintRequest, opts ...grpc.CallOption) (*PrintReply, error)
	PrintSetVoice(ctx context.Context, in *PrintSetVoiceRequest, opts ...grpc.CallOption) (*PrintReply, error)
}

type printServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrintServiceClient(cc *grpc.ClientConn) PrintServiceClient {
	return &printServiceClient{cc}
}

func (c *printServiceClient) Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/proto.PrintService/Print", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *printServiceClient) GetForeignToken(ctx context.Context, in *ForeignOauthRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/proto.PrintService/GetForeignToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *printServiceClient) GetToken(ctx context.Context, in *OauthRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/proto.PrintService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *printServiceClient) PicturePrint(ctx context.Context, in *PicturePrintRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/proto.PrintService/PicturePrint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *printServiceClient) ExpressPrint(ctx context.Context, in *ExpressPrintRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/proto.PrintService/ExpressPrint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *printServiceClient) PrintSetVoice(ctx context.Context, in *PrintSetVoiceRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/proto.PrintService/PrintSetVoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrintServiceServer is the server API for PrintService service.
type PrintServiceServer interface {
	Print(context.Context, *PrintRequest) (*PrintReply, error)
	GetForeignToken(context.Context, *ForeignOauthRequest) (*PrintReply, error)
	GetToken(context.Context, *OauthRequest) (*PrintReply, error)
	PicturePrint(context.Context, *PicturePrintRequest) (*PrintReply, error)
	ExpressPrint(context.Context, *ExpressPrintRequest) (*PrintReply, error)
	PrintSetVoice(context.Context, *PrintSetVoiceRequest) (*PrintReply, error)
}

// UnimplementedPrintServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrintServiceServer struct {
}

func (*UnimplementedPrintServiceServer) Print(ctx context.Context, req *PrintRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Print not implemented")
}
func (*UnimplementedPrintServiceServer) GetForeignToken(ctx context.Context, req *ForeignOauthRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForeignToken not implemented")
}
func (*UnimplementedPrintServiceServer) GetToken(ctx context.Context, req *OauthRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (*UnimplementedPrintServiceServer) PicturePrint(ctx context.Context, req *PicturePrintRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PicturePrint not implemented")
}
func (*UnimplementedPrintServiceServer) ExpressPrint(ctx context.Context, req *ExpressPrintRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpressPrint not implemented")
}
func (*UnimplementedPrintServiceServer) PrintSetVoice(ctx context.Context, req *PrintSetVoiceRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintSetVoice not implemented")
}

func RegisterPrintServiceServer(s *grpc.Server, srv PrintServiceServer) {
	s.RegisterService(&_PrintService_serviceDesc, srv)
}

func _PrintService_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintServiceServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrintService/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintServiceServer).Print(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrintService_GetForeignToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForeignOauthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintServiceServer).GetForeignToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrintService/GetForeignToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintServiceServer).GetForeignToken(ctx, req.(*ForeignOauthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrintService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OauthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrintService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintServiceServer).GetToken(ctx, req.(*OauthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrintService_PicturePrint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PicturePrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintServiceServer).PicturePrint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrintService/PicturePrint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintServiceServer).PicturePrint(ctx, req.(*PicturePrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrintService_ExpressPrint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpressPrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintServiceServer).ExpressPrint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrintService/ExpressPrint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintServiceServer).ExpressPrint(ctx, req.(*ExpressPrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrintService_PrintSetVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintSetVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintServiceServer).PrintSetVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PrintService/PrintSetVoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintServiceServer).PrintSetVoice(ctx, req.(*PrintSetVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrintService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PrintService",
	HandlerType: (*PrintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Print",
			Handler:    _PrintService_Print_Handler,
		},
		{
			MethodName: "GetForeignToken",
			Handler:    _PrintService_GetForeignToken_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _PrintService_GetToken_Handler,
		},
		{
			MethodName: "PicturePrint",
			Handler:    _PrintService_PicturePrint_Handler,
		},
		{
			MethodName: "ExpressPrint",
			Handler:    _PrintService_ExpressPrint_Handler,
		},
		{
			MethodName: "PrintSetVoice",
			Handler:    _PrintService_PrintSetVoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/print.proto",
}
